artifact_uri: file:///C:/Users/Sanjeet/PycharmProjects/mlflow/LoggingFunction/myartifacts/92c850dfd8ee4721a282b93e8e51c0ed/artifacts
end_time: 1700438497480
entry_point_name: ''
experiment_id: '114638063360247726'
lifecycle_stage: active
run_id: 92c850dfd8ee4721a282b93e8e51c0ed
run_name: debonair-skink-442
run_uuid: 92c850dfd8ee4721a282b93e8e51c0ed
source_name: ''
source_type: 4
source_version: ''
start_time: 1700438495788
status: 3
tags: []
user_id: Sanjeet
