artifact_uri: file:///C:/Users/Sanjeet/PycharmProjects/mlflow/LoggingFunction/mytracking/184649666270221314/cbbadef7293a42d6aabb29ff8318bf21/artifacts
end_time: 1700435817578
entry_point_name: ''
experiment_id: '184649666270221314'
lifecycle_stage: active
run_id: cbbadef7293a42d6aabb29ff8318bf21
run_name: wise-owl-64
run_uuid: cbbadef7293a42d6aabb29ff8318bf21
source_name: ''
source_type: 4
source_version: ''
start_time: 1700435815933
status: 3
tags: []
user_id: Sanjeet
