artifact_location: file:///C:/Users/Sanjeet/PycharmProjects/mlflow/LoggingFunction/myartifacts
creation_time: 1700438495548
experiment_id: '114638063360247726'
last_update_time: 1700438495548
lifecycle_stage: active
name: myexperiment1
