artifact_location: file:///C:/Users/Sanjeet/PycharmProjects/mlflow/LoggingFunction/mytracking/0
creation_time: 1700435815711
experiment_id: '0'
last_update_time: 1700435815711
lifecycle_stage: active
name: Default
