artifact_location: file:///C:/Users/Sanjeet/PycharmProjects/mlflow/LoggingFunction/mytracking/184649666270221314
creation_time: 1700435815719
experiment_id: '184649666270221314'
last_update_time: 1700435815719
lifecycle_stage: active
name: experiment_1
